http:
  port: ${HTTP_POST:-8080}
admin:
  port: ${ADMIN_PORT:-9876}
  # Setting host to 0.0.0.0 is required to make the admin port available on localhost from outside the container on Mac OSX
  # But if the admin API is behind a gateway, the default setting works on OSX
  # host: '0.0.0.0' # default value is 'localhost'
apiEndpoints:
  api:
    host: localhost
    paths:
      - '/ip'
      - '/headers'
  admin-api:
    host: localhost
    paths: '/admin*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  admin:
    url: 'http://localhost:9876'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - example
  - rewrite
pipelines:
  getting-started:
    apiEndpoints:
      - api
    policies:
      # - key-auth:
      # - rate-limit:
      #     - action:
      #         max: 1
      #         windowMs: 5000
      # - example:
      #   - action:  # everything under the action will be actionParams
      #         baseUrl: 'https://example.com'
      - rewrite:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  admin:
    apiEndpoints:
      - admin-api
    policies:
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: admin
              stripPath: true
              changeOrigin: true
