http:
  port: ${HTTP_POST:-8080}
admin:
  port: ${ADMIN_PORT:-9876}
  host: '0.0.0.0'
apiEndpoints:
  api:
    host: localhost
    paths:
      - '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - example
  - rewrite
pipelines:
  - name: getting-started
    apiEndpoints:
      - api
    policies:
      # - key-auth:
      # - rate-limit:
      #     - action:
      #         max: 1
      #         windowMs: 5000
      # - example:
      #   - action:  # everything under the action will be actionParams
      #         baseUrl: 'https://example.com'
      - rewrite:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true